"""Add func target type

Revision ID: 3284fd5dff8b
Revises: fe3890ca251c
Create Date: 2024-09-19 17:21:52.921314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3284fd5dff8b'
down_revision: Union[str, None] = 'fe3890ca251c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servant_buffs', sa.Column('function_target_type', sa.String(length=255), nullable=True, comment='效果对目标的影响'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servant_buffs', 'function_target_type')
    # ### end Alembic commands ###
