"""add ce

Revision ID: 3af4098aea65
Revises: 2e08288cb072
Create Date: 2024-09-20 15:53:08.809460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af4098aea65'
down_revision: Union[str, None] = '2e08288cb072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_essence',
    sa.Column('ce_id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('ce_name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('buff_name', sa.String(length=255), nullable=False, comment='buff名称'),
    sa.Column('buff_type', sa.String(length=255), nullable=False, comment='buff类型'),
    sa.Column('value', sa.Integer(), nullable=False, comment='buff值'),
    sa.Column('turn', sa.Integer(), nullable=False, comment='buff持续回合数'),
    sa.Column('cost', sa.Integer(), nullable=False, comment='消耗'),
    sa.Column('max_atk', sa.Integer(), nullable=False, comment='buff对攻击力的影响'),
    sa.PrimaryKeyConstraint('ce_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('craft_essence')
    # ### end Alembic commands ###
