"""update buffs

Revision ID: 7065f68cf2aa
Revises: 58e1a9927420
Create Date: 2024-09-20 15:37:30.748569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7065f68cf2aa'
down_revision: Union[str, None] = '58e1a9927420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servant_buffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servant_buffs',
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('servant_id', sa.INTEGER(), nullable=False),
    sa.Column('servant_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('skill_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('skill_no', sa.INTEGER(), nullable=False),
    sa.Column('buff_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('buff_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('function_target_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('function_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('function_target_traits', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('turn', sa.INTEGER(), nullable=True),
    sa.Column('rate', sa.INTEGER(), nullable=True),
    sa.Column('userate', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###
