"""recreate buff table

Revision ID: 8c9fa7164aa4
Revises: dc3feb499724
Create Date: 2024-09-19 17:29:30.435498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9fa7164aa4'
down_revision: Union[str, None] = 'dc3feb499724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servant_buffs',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False, comment='记录id'),
    sa.Column('servant_id', sa.Integer(), nullable=False, comment='从者id'),
    sa.Column('servant_name', sa.String(length=255), nullable=False, comment='从者中文名'),
    sa.Column('skill_type', sa.String(length=255), nullable=True, comment='技能类型'),
    sa.Column('skill_no', sa.Integer(), nullable=False, comment='技能序号'),
    sa.Column('buff_name', sa.String(length=255), nullable=True, comment='buff名称'),
    sa.Column('buff_type', sa.String(length=255), nullable=True, comment='buff类型'),
    sa.Column('function_target_type', sa.String(length=255), nullable=True, comment='效果对目标的影响'),
    sa.Column('function_type', sa.String(length=255), nullable=True, comment='效果类型'),
    sa.Column('function_target_traits', sa.String(length=255), nullable=True, comment='效果对特性的影响'),
    sa.Column('value', sa.Integer(), nullable=True, comment='buff值'),
    sa.Column('count', sa.Integer(), nullable=True, comment='buff次数'),
    sa.Column('turn', sa.Integer(), nullable=True, comment='buff持续回合数'),
    sa.Column('rate', sa.Integer(), nullable=True, comment='buff命中率'),
    sa.Column('userate', sa.Integer(), nullable=True, comment='buff生效几率'),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servant_buffs')
    # ### end Alembic commands ###
