"""Initial schema

Revision ID: c300e962b967
Revises: 
Create Date: 2024-09-19 15:33:57.858227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c300e962b967'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loopers',
    sa.Column('id', sa.Integer(), nullable=False, comment='从者id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='从者中文名'),
    sa.Column('rarity', sa.Integer(), nullable=False, comment='星级'),
    sa.Column('class_name', sa.String(length=255), nullable=False, comment='职介'),
    sa.Column('tendancy', sa.Integer(), nullable=False, comment='攻防总倾向'),
    sa.Column('np_rate', sa.Float(), nullable=False, comment='NP获取率'),
    sa.Column('np_hits', sa.String(length=255), nullable=False, comment='NP命中数'),
    sa.Column('is_strengthened', sa.Boolean(), nullable=False, comment='是否已强化'),
    sa.Column('class_mod', sa.Integer(), nullable=False, comment='职介补正'),
    sa.Column('attribute', sa.String(length=255), nullable=False, comment='阵营'),
    sa.Column('traits', sa.String(length=255), nullable=False, comment='特性'),
    sa.Column('star_absorb', sa.Integer(), nullable=False, comment='集星率'),
    sa.Column('star_gen', sa.Integer(), nullable=False, comment='打星率'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servant_buffs',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False, comment='记录id'),
    sa.Column('servant_id', sa.Integer(), nullable=False, comment='从者id'),
    sa.Column('servant_name', sa.String(length=255), nullable=False, comment='从者中文名'),
    sa.Column('skill_type', sa.String(length=255), nullable=True, comment='技能类型'),
    sa.Column('skill_no', sa.Integer(), nullable=False, comment='技能序号'),
    sa.Column('buff_name', sa.String(length=255), nullable=False, comment='buff名称'),
    sa.Column('buff_type', sa.String(length=255), nullable=False, comment='buff类型'),
    sa.Column('function_type', sa.String(length=255), nullable=True, comment='效果类型'),
    sa.Column('function_target_traits', sa.String(length=255), nullable=True, comment='效果对特性的影响'),
    sa.Column('value', sa.Integer(), nullable=True, comment='buff值'),
    sa.Column('count', sa.Integer(), nullable=True, comment='buff次数'),
    sa.Column('turn', sa.Integer(), nullable=True, comment='buff持续回合数'),
    sa.Column('rate', sa.Integer(), nullable=True, comment='buff命中率'),
    sa.Column('userate', sa.Integer(), nullable=True, comment='buff生效几率'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('supports',
    sa.Column('id', sa.Integer(), nullable=False, comment='从者id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='从者中文名'),
    sa.Column('rarity', sa.Integer(), nullable=False, comment='星级'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supports')
    op.drop_table('servant_buffs')
    op.drop_table('loopers')
    # ### end Alembic commands ###
