"""delete old buff table

Revision ID: dc3feb499724
Revises: 3284fd5dff8b
Create Date: 2024-09-19 17:29:08.044634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3feb499724'
down_revision: Union[str, None] = '3284fd5dff8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servant_buffs_new')
    op.drop_table('servant_buffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servant_buffs',
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('servant_id', sa.INTEGER(), nullable=False),
    sa.Column('servant_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('skill_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('skill_no', sa.INTEGER(), nullable=False),
    sa.Column('buff_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('buff_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('function_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('function_target_traits', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('turn', sa.INTEGER(), nullable=True),
    sa.Column('rate', sa.INTEGER(), nullable=True),
    sa.Column('userate', sa.INTEGER(), nullable=True),
    sa.Column('function_target_type', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('servant_buffs_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('buff_name', sa.VARCHAR(), nullable=True),
    sa.Column('buff_value', sa.FLOAT(), nullable=True),
    sa.Column('buff_type', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
